export const HOME = '/'
export const CONTACT = '/contact'
export const FACILITY = '/facility'
export const ABOUT = '/about'
export const SERVICES = '/services'
export const DIFFERENCE = '/our-difference'
