export { default as Header} from './header'
export { default as Hero} from './hero'
export { default as Services } from './services'
export { default as Footer } from './footer'
export { default as About} from './about'
export { default as Contact } from './contact'