export { default as Header} from './header'
export { default as Hero} from './hero'
export { default as Services } from './homeServices'
export { default as Footer } from './footer'
export { default as About} from './homeAbout'
export { default as ContactForm } from './contactForm'
export { default as Staff } from './staff'
export { default as LearnMore } from './learnMore'
export { default as Quote } from './quote'
export { default as Gallery } from './gallery'
export { default as Location } from './location'
export { default as Carousel } from './carousel'